### PR TITLE
179 revise one click button css

### PR DESCRIPTION
**Pull request by Sporradik**
Not quite done yet, but you can take a look

Screenshot 2024-10-14 at 9 46 59 PM

### CODE REVIEW

**Comment by emcniece** [comment]
Haven't had a chance to look at this yet but since you're already working in here - any considerations for mobile viewports?

**Comment by Sporradik** [comment]
Alrighty, addressed feedback and removed the hover only visibility.

**Suggestion:**

One thing that could be nice is to have no value in the input by default and then use the placeholder value if nothing is selected. I tried changing the behaviour to select all text when focused, but it didn't feel quite right as it was less obvious that it was an input. Using the placeholder value would just remove the step of having to clear the input if entering a different value because IMO it's more likely you'd want that then to be appending to the value.

**Comment by sabjorn** [comment]
@Sporradik I feel you on that -- it is definitely cumbersome to change the price. I'll play with it a bit and see if I can figure something out

**Review by sabjorn — APPROVED** [review]

**Comment by sabjorn** [comment]
LGTM -- merge whenever you're ready

**Pull request merged**
